### ISSUE TITLE
docs: cool logo

### ISSUE THREAD

**Issue by KennethEnevoldsen** [Aarhus-Psychiatry-Research/timeseriesflattener#13]

**Comment by KennethEnevoldsen** [comment]
Two suggestions:

## 1) 

<img width="1219" alt="Screenshot 2022-12-09 at 11 24 58" src="https://user-images.githubusercontent.com/23721977/206693872-c6305d41-be86-45d8-9ec5-cbc0b984faf1.png">

## 2)

<img width="1234" alt="Screenshot 2022-12-09 at 11 25 03" src="https://user-images.githubusercontent.com/23721977/206693887-a7f8fd45-8e1e-4354-a251-e199b0664c84.png">

## And some more variations a)-d):

<img width="1170" alt="Screenshot 2022-12-09 at 11 37 43" src="https://user-images.githubusercontent.com/23721977/206693903-a1cf646e-7d10-479e-9996-3ca5d37ab281.png">

**Comment by MartinBernstorff** [comment]
Hahaha, damn, I've also been working on something:

![Image](https://user-images.githubusercontent.com/8526086/206694240-fe074163-4e7d-41a2-ad1e-d17b51ab9f2f.png)

**Comment by KennethEnevoldsen** [comment]
Good with some friendly competition ;)

**Comment by MartinBernstorff** [comment]
Haha, absolutely. I'm up for whatever, we can let the others decide ;-)

**Comment by MartinBernstorff** [comment]
@frillecode @HLasse @bokajgd Comment/votes? 😁

**Comment by MartinBernstorff** [comment]
@KennethEnevoldsen Ikke det store uptake på kommentarer her. Skal vi ikke bare vælge en? 

Jeg hælder (ikke så overraskende) til min egen ;-)

**Comment by KennethEnevoldsen** [comment]
Jamen det er jo problemet, jeg kan meget godt lige min egen - laver en poll

**Comment by MartinBernstorff** [comment]
The people have spoken! Du går bare amok ;-)
