### ISSUE TITLE
Extend testing to all existing/supported Pythons and other OSes

### ISSUE THREAD

**Issue by yarikoptic** [Aarhus-Psychiatry-Research/timeseriesflattener#133]
ATM looking at https://github.com/Aarhus-Psychiatry-Research/timeseriesflattener/blob/main/.github/workflows/main_test_and_release.yml#L19 it is only 3.9 and on ubuntu .

https://github.com/Aarhus-Psychiatry-Research/timeseriesflattener/blob/main/pyproject.toml#L11 makes claim that it supports 3.8+ python and no os restrictions.

Would be nice if testing was aligned: test for all supported python versions and across OSes. You already have matrix setup in that workflow, so just a matter of slight improvement.  If other OSes/versions not supported -- pyproject.toml should reflect that I guess to avoid user suprises.

**Comment by MartinBernstorff** [comment]
This is a great point. We're running out of testing credits if we include macOS and Windows atm., but will definitely add python 3.10 and 3.11. Working on it in #136.
