### ISSUE TITLE
Paper: Please add captions to the tables

### ISSUE THREAD

**Issue by mstimberg** [Aarhus-Psychiatry-Research/timeseriesflattener#154]
[Finalizing the review for JOSS: https://github.com/openjournals/joss-reviews/issues/5197]

Could you please add (short) captions to the two tables in the paper so that they get numbered as Table 1 and Table 2 (since you refer to them earlier):
> A caption is a paragraph beginning with the string Table: (or table: or just :), which will be stripped off. It may appear either before or after the table.

https://pandoc.org/MANUAL.html#extension-table_captions

**Comment by MartinBernstorff** [comment]
@HLasse Will you take a look? :-)
