### ISSUE TITLE
Paper: minor reference fixes

### ISSUE THREAD

**Issue by mstimberg** [Aarhus-Psychiatry-Research/timeseriesflattener#155]
[Finalizing the review for JOSS: https://github.com/openjournals/joss-reviews/issues/5197]

- Could you please add a "References" section header before the reference list
- The reference for XGBboost looks a bit odd and references a rather old version. Since you seem to cite it in a general way, I think it would be better to use the citation that the developers suggest: https://github.com/dmlc/xgboost/blob/master/CITATION
- Could you add the DOI (`10.1109/RBME.2020.3007816`) to the reference for the Shamout et al. IEEE paper? The correct year also seems to be 2021not 2020 (https://ieeexplore.ieee.org/document/9134853)

**Comment by MartinBernstorff** [comment]
Excellent points, fixing now.

**Comment by mstimberg** [comment]
Looks good in general, but the Shamout et al. reference still has the year as 2020 instead of 2021 in the `.bib` file, and its citation is currently broken (should use `@shamout_machine_2021` instead of `@shamout_machine_2020` now).

**Comment by MartinBernstorff** [comment]
Sorry about that, fixed in [f26a37d](https://github.com/Aarhus-Psychiatry-Research/timeseriesflattener/commit/f26a37d8547031fdb8a10d2ab4fc9827cee6de90).
