### ISSUE TITLE
feat: take multiple features as long format

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/timeseriesflattener#37]

**Comment by MartinBernstorff** [comment]
Mega godt forslag. Tænker vi skal finde ud af om det her er need-to-have før submit til JOSS og om

**Comment by MartinBernstorff** [comment]
Et forslag:

1. Find alle unique "value_names" i df'en som long
2. Gem dem hver for sig som dfs i et catalogue
3. Tilføj lookup i det registry til feature_spec objekterne. Raise en error hvis en streng findes både som loader funktion og som df i cataloguet.
