### ISSUE TITLE
feat: add all aggregators from v1

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/timeseriesflattener#396]
This is non-trivial with the current Aggregator interface. 

E.g.: `latest` requires getting a grouped dataframe. That should be possible, but I'd like to talk to you about it @HLasse. 

It will cost some performance.

**Comment by HLasse** [comment]
Not sure I follow - they already receive a grouped dataframe. 

https://github.com/Aarhus-Psychiatry-Research/timeseriesflattener/blob/40e5023c1d80446cf1c5079d535c8b555e76b1e2/src/timeseriesflattenerv2/_process_spec.py#L108-L110

So I assume [`pl.last`](https://docs.pola.rs/py-polars/html/reference/expressions/api/polars.last.html) should do the trick?

**Comment by MartinBernstorff** [comment]
Right now, the aggregators should return a `pl.Expr` which can be evaluated within the `.agg` context. I don't think `.last` satisfies that, but definitely worth a try!

If not, we can just change the interface so they get a grouped frame 👍

**Comment by HLasse** [comment]
Ah, I see what you mean. Yeah, let's give a try and change it up if it doesn't work

**Comment by MartinBernstorff** [comment]
They work within the `.agg` context! Now the only problem is that we assume that the dataframe is sorted by date, which it isn't necessarily.

I'll take a look. Just to get an overview of what we need to implement:
* `earliest` - requires sorting
* `latest` - requires sorting
* `summed`
* `variance`
* `boolean`
* `change_per_day` - requires access to the entire grouped df
