### ISSUE TITLE
only print warning if OS is Windows

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/timeseriesflattener#454]
```
        if self.compute_lazily: # TODO only print this if OS is Windows
```

https://github.com/Aarhus-Psychiatry-Research/timeseriesflattener/blob/86e1475ca73c800e03d48d9c970751d91d503633/src/timeseriesflattenerv2/flattener.py#L85

**Comment by MartinBernstorff** [comment]
It might also be a scale thing - since we don't know the source of the problem, I think we should keep warning in general for now 👍
