### ISSUE TITLE
Update basic tutorial with 1) gdocs and 2) comments from Andreas (waiting on Andreas)

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/timeseriesflattener#46]
Giving comments to a jupyter notebook in git sucks, so I've copy/pasted it into a google doc. Suggested workflow is to read the [google doc](https://docs.google.com/document/d/1Fn7zsomGtXO15-4KY63Lgrxe0ZeDgnbrVsl0wfofJUQ/edit?usp=sharing) and make comments in it, but to check the [rendered file](https://github.com/Aarhus-Psychiatry-Research/timeseriesflattener/blob/main/tutorials/01_basic.ipynb) for the outputs.

**Comment by HLasse** [comment]
This can be closed, right?
