### ISSUE TITLE
feat: timedelta inference

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/timeseriesflattener#461]
Investigate if we can automatically infer the best format to return TimeDelta columns from. E.g. if the smallest values are days, we should probably return in days

**Comment by HLasse** [comment]
On further thought, I think we should have the user specify this. Inferring this could easily lead to confusion and unexpected behaviour if our inference does not align with expectations. I imagine supporting `[seconds, minutes, days, years]` and defaulting to `years`. @MartinBernstorff, thoughts?

**Comment by MartinBernstorff** [comment]
I think we should support an override, but infer it by default. 

Having to specify it all the time can quickly get annoying, and then users can subclass to override by default. 

How does that sound? 😊

**Comment by MartinBernstorff** [comment]
Stick to days, good trade-off of doing nothing.
