### ISSUE TITLE
fix: pure NaNs when flattening with lookbehind-tuple in 01_basic

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/timeseriesflattener#480]
@HLasse Not sure what is going on here, any ideas?

**Comment by HLasse** [comment]
Nasty little bug in `_get_timedelta_frame` if the timestamp column in  `predictiontime_frame´ and `value_frame` had the same name meant that the timedelta would always be 0 in that case.
