### ISSUE TITLE
feat: check that all `entity_id_col_name`s in specs and predictime_frame are the same

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/timeseriesflattener#491]
Currently, `entity_id_col_name` has to be specified for each spec AND in the `predictiontime_frame`. However, when we merge, these col names have to match (which we don't check right now). '

It seems like a reasonable assumption that if the `entity_id_col_name` is not the same across specs and predictiontime_frames, then there is an user error. Therefore, I propose that we don't explicitly set `entity_id_col_name` in the specs, but instead supply it during flattening (similar to what we do in v1).

Added benefit of having significantly less duplication for the users. If we check that all specs have the right entity id column before flattening I don't there being an issue. @MartinBernstorff ?

**Comment by MartinBernstorff** [comment]
For now, we agreed to still having to specify it, in the spirit of "all required columns should be present as attributes in the specification frame".

**Comment by MartinBernstorff** [comment]
Functionality was already present in `_specs_contain_required_columns` 👍
