### ISSUE TITLE
feat: check that aggregation function, lookdistance etc are sequences

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/timeseriesflattener#494]
Users might ignore type errors - better to ensure that they don't get unexpected errors

**Comment by MartinBernstorff** [comment]
Hmm, I'm not sure I agree here. Most other libraries don't do this kind of checking.

One "easy" solution would be to use Pydantic, but I would love to avoid that, namely due to its errors with `from __future__ import annotations`.
