### ISSUE TITLE
fix: timestamp column names must be different between pred_ and value frames if using aggregators that take `timestamp_col_name`

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/timeseriesflattener#498]
Martin: 
> Rather, we only need the column names to be different when calculating the timedelta. 
> So generate a temporary df used for calculating timedeltas, but let the rest be unmodified. That should solve the problem.

If we change the name of a timestamp column during merging, the timestamp supplied to e.g. `LatestAggregator` is no longer valid. Instead, we should probably require (and check) that the timestamp column supplied to the `PredictionTimeFrame` is different to the timestamp column supplied in the `ValueFrame`s

**Comment by MartinBernstorff** [comment]
Rather, we only need the column names to be different when calculating the timedelta. 

So generate a temporary df used for calculating timedeltas, but let the rest be unmodified. That should solve the problem.
