### ISSUE TITLE
fix: simplify public-facing types by inlining type-aliases

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/timeseriesflattener#514]
E.g. `init_df` of `ValueFrame|TimestampValueFrame` takes an `InitDF_T` which is hard to parse without a doc string specifying it or by changing the type to be human readable. 

Others:

- [x] look[behind|ahead] distance: `LookDistances` (sequence of dt.timedelta)
- [x] fallback: ValueType 
- [x] entity_id_col_name: default_entity_id_col_name (instead of the string repr)
- [x] default_pred_time_col_name
- [x] default_prediction_time_uuid_col_name
- [x] default_timestamp_col_name

**Comment by HLasse** [comment]
@MartinBernstorff are you on board with inlining the type aliases? As we discussed, it makes it easier for the user, but a bit less nice for developers. I think it's a worthy trade-off in this case, though

**Comment by MartinBernstorff** [comment]
If you have a strong opinion, I'm OK with that 👍

**Comment by HLasse** [comment]
I've added a quick PR  (#564) for the types outlined above to get a feel for how it would look. Some of the types were only used in one place, but I completely get the worry that more widely used types can potentially drift. It does it make it substantially easier for users, though. Have a look and let's talk about it at some point
