### ISSUE TITLE
docs: update advanced tutorial with comments from basic tutorial (waiting on basic tutorial completion)

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/timeseriesflattener#53]
Use also this: 

![](img/term_d.png)

We set `drop_pred_times_with_insufficient_look_distance` to true. This means prediction times are dropped if the *lookbehind* extends further back in time than the start of the dataset or if the *lookahead* extends further than the end of the dataset. 

For most applications, this should be true - you do not want features to say they're looking a year into the future, if you only have a month of data. This would compromise generalisability. However, there are some edge cases where you might want this to be false - see the advanced tutorial for a brief discussion on this.

However, there is a trade-off here. Longer lookbehinds mean that each feature is more informative. Shorter lookbehinds mean that you get to keep more of your data. You might want to explore this tradeoff when you're training your models. If that is the case, you need to do this filtering manually - but you might not want it to be done right now.

**Comment by HLasse** [comment]
Can we close this?
