### ISSUE TITLE
Multiprocessing=None fixes WinError 87

### ISSUE THREAD

**Issue by sarakolding** [Aarhus-Psychiatry-Research/timeseriesflattener#532]
Why does setting multiprocessing to None fix `OSError: [WinError 87] The parameter is incorrect`?

@HLasse did you encounter this when generating features?

**Comment by HLasse** [comment]
I need a bit more context for this - when does this happen? Feature generation with large datasets? Vague recollection of it, but unsure, sorry!

**Comment by sarakolding** [comment]
sorry, that was very little information to go by. happens when trying to flatten features - seems independent of dataset size and individual project differences (i could not run your features either).
