### ISSUE TITLE
Idea: Make `ValueFrame` a sequence

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/timeseriesflattener#548]
Back in the day, we could use the `PredictorGroupSpec` to make combinations of all variables, both input dataframes, lookbehinds etc. Now, we can do the same without the GroupSpec, _except_ making the same combination of lookbehinds, fallbacks.. on a number of input dataframes. 

This is useful e.g. for making features for diagnoses which could previously be done like this:
```python
psychiatric_diagnoses = list(
    PredictorGroupSpec(
        named_dataframes=(
            NamedDataframe(df=f0_disorders(), name=f"f0_disorders"),
            NamedDataframe(df=f1_disorders(), name=f"f1_disorders"),
            NamedDataframe(df=f2_disorders(), name=f"f2_disorders"),
            NamedDataframe(df=f3_disorders(), name=f"f3_disorders"),
            NamedDataframe(df=f4_disorders(), name=f"f4_disorders"),
            NamedDataframe(df=f5_disorders(), name=f"f5_disorders"),
            NamedDataframe(df=f6_disorders(), name=f"f6_disorders"),
            NamedDataframe(df=f7_disorders(), name=f"f7_disorders"),
            NamedDataframe(df=f8_disorders(), name=f"f8_disorders"),
            NamedDataframe(df=f9_disorders(), name=f"f9_disorders"),
        ),
        lookbehind_days=[730],
        aggregation_fns=[boolean],
        fallback=[0],
    ).create_combinations()
```
Now, we have to make a separate `PredictorSpec` for each (or use the legacy group spec) which is a bit cumbersome. 

Thoughts, @sarakolding, @MartinBernstorff?

**Comment by MartinBernstorff** [comment]
My intuition is that this is a relatively rare use-case, and very easy to wrap.

With that said, because it is so easy to wrap, we could easily support it in the outer function – create all the different combinations, and then split them out to separate processes in the pool.

I'm up for adding it, if you think we need it 👍

**Comment by HLasse** [comment]
Given that it's so easy to wrap I don't think it's worth the refactoring and code changes - let's bring it up again if someone besides me wants it ;)
