### ISSUE TITLE
Understanding of bug #559.

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/timeseriesflattener#561]
Completely understand the merge here! #560

@HLasse, just adding some discussion here. Not sure I understand the fix. 

Don't the temporal and static paths of the flattening get the prediction times in the same order, regardless of whether they are sorted or not?

**Comment by HLasse** [comment]
Yes and no. Only the temporal specs use the `step_size` argument; static does not. This means that the temporal specs will output the rows in the order of the prediction times, but sorted by the steps (e.g. if step_size=1 year, 2013 first, 2014, ...). If prediction times are not temporally ordered there will therefore be a mismatch between the output of temporal and static specs.

**Comment by MartinBernstorff** [comment]
Ohhh, I see! Of course, this results in implicit sorting. Great catch, and thanks _so much_ for fixing it. Apologies for introducing this bug, neither our unit tests, nor @sarakolding or I caught it. 

As a learning experience, this indicates the need for interaction-testing. Really happy you added that here.

**Comment by HLasse** [comment]
Yeah, a sneaky one!! Goes to show the value of collaborative work ❤️
