### ISSUE TITLE
Add `TextSpec` to handle embedding of text-features

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/timeseriesflattener#97]
Suggested API:

```python
class TextPredictorSpec(PredictorSpec):
    embedding_fn: str | Callable # function to use for embedding the text, e.g. a function calling an sklearn TF-IDF pipeline
    dim_reduction_fn: Optional[Callable] # function to reduce the dimensionalty of the text embedding (e.g. UMAP)
    resolve_multiple_fn: str | Callable = ["concatenate"] # how to combine texts within the lookbehind window
```

Things to consider:

- [x] Call embedding function if TextPredictorSpec in `_flatten_temporal_values_to_df`
- [x] Renaming of multiple columns. Overwrite `get_col_str` for `TextPredictorSpec`to handle multiple columns
- [x] Fallback. Do we need to know the dimensionality to add fallback values? 
- [ ] Cache functionality?

TODO:
- [X] Set up development pipeline (synth data, small BOW model)
- [X] Create "concatenate" resolve_multiple_fn
- [x] Create test for embedding_fn

Development branch: https://github.com/Aarhus-Psychiatry-Research/timeseriesflattener/tree/HLasse/Add-%60TextSpec%60-to-handle-embedding-of-text-features

**Comment by HLasse** [comment]
@frillecode let's loop Martin in before we take this up again. Hit us up when you're back from vacation 🏖️

**Comment by HLasse** [comment]
Try to keep the flow for handling multiple columns in PredictorSpec - opens the door for e.g. using multiple resolve fns.

**Comment by MartinBernstorff** [comment]
> Try to keep the flow for handling multiple columns in PredictorSpec - opens the door for e.g. using multiple resolve fns.

Or at least keep it compatible with `PredictorSpec` - the logic should probably be in `timeseriesflattener` :-)

**Comment by frillecode** [comment]
@HLasse. I'm back now, but it seems that you've already closed the issue, right?
